/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-06 03:24:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.model.*;
import java.util.*;
import com.dao.*;
import com.db.*;
import java.text.DecimalFormat;

public final class cart_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/includes/navbar.jsp", Long.valueOf(1664589626069L));
    _jspx_dependants.put("/includes/header.jsp", Long.valueOf(1664111128382L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.db");
    _jspx_imports_packages.add("com.dao");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.model");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.text.DecimalFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

DecimalFormat d = new DecimalFormat("#.##");
request.setAttribute("deci", d);

User auth = (User) request.getSession().getAttribute("auth");

if (auth != null) {
	request.setAttribute("auth", auth);

}

ArrayList<Cart> cart_list = (ArrayList<Cart>) session.getAttribute("cart-list");

List<Cart> cartProduct = null;

if (cart_list != null) {
	ProductDao pDao = new ProductDao(dbConnect.getConnection());
	cartProduct = pDao.getCartProducts(cart_list);

	double total = pDao.getCartTotal(cartProduct);

	request.setAttribute("cart_list", cart_list);
	request.setAttribute("total", total);
}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Cart Page</title>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write(".table tbody td {\n");
      out.write("	vertical-align: middle;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".btn-incre, .btn-decre {\n");
      out.write("	box-shodow: none;\n");
      out.write("	font-size: 20px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\"\n");
      out.write("	integrity=\"sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==\"\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<link rel=\"stylesheet\"\n");
      out.write("	href=\"	https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css\"\n");
      out.write("	integrity=\"sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==\"\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js\" integrity=\"sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13\" crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("<script\n");
      out.write("	src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/js/brands.min.js\"\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("	\n");
      out.write("\n");
      out.write("<!-- <link\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\"\n");
      out.write("	rel=\"stylesheet\"\n");
      out.write("	integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css\"\n");
      out.write("	integrity=\"sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==\"\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\n");
      out.write("\n");
      out.write("<script\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("	integrity=\"sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM\"\n");
      out.write("	crossorigin=\"anonymous\"></script> -->");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	");
      out.write("\n");
      out.write("<div class=\"container-fluid bg-primary\">\n");
      out.write("\n");
      out.write("<div class=\"row\">\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("<div class=\"row\">\n");
      out.write("\n");
      out.write("<div class=\"col-12\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark\">\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<a class=\"navbar-brand\" href=\"index.jsp\"><i class=\"fa-solid fa-cart-arrow-down\"></i>\n");
      out.write("		Shopping Cart</a>\n");
      out.write("		<button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("			data-bs-target=\"#navbarSupportedContent\"\n");
      out.write("			aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\n");
      out.write("			aria-label=\"Toggle navigation\">\n");
      out.write("			<span class=\"navbar-toggler-icon\"></span>\n");
      out.write("		</button>\n");
      out.write("\n");
      out.write("		<div class=\"collapse navbar-collapse justify-content-end\" id=\"navbarSupportedContent\">\n");
      out.write("\n");
      out.write("			<!--      <ul class=\"navbar-nav \"> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("			<ul class=\"navbar-nav\">\n");
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link active\"\n");
      out.write("					href=\"index.jsp\">Home</a></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"cart.jsp\">Cart<span class=\"badge bg-success\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cart_list.size()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span></a></li>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				");

				if (auth != null) {
				
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"orders.jsp\">Order</a>\n");
      out.write("				</li>\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"userLogout\">Logout</a>\n");
      out.write("				</li>\n");
      out.write("\n");
      out.write("\n");
      out.write("				");

				} else {
				
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				<li class=\"nav-item\"><a class=\"nav-link\" href=\"login.jsp\"><i class=\"fa-solid fa-right-to-bracket\"></i>Login</a>\n");
      out.write("				</li>\n");
      out.write("\n");
      out.write("				");

				}
				
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("			</ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("		</div>\n");
      out.write("		\n");
      out.write("	\n");
      out.write("	</div>\n");
      out.write("</nav>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write(" ");
      out.write("\n");
      out.write("\n");
      out.write("	<div class=\"container\">\n");
      out.write("		<div class=\"d-flex py-4\">\n");
      out.write("			<h5>Total Price :$ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(total >0)?deci.format(total):0 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\n");
      out.write("			<a href=\"checkOut\" class=\"mx-4 btn btn-info mb-2\">Check Out</a>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<!-- <table class=\"table table-dark table-striped\">  -->\n");
      out.write("		<!-- table class=\"table table-success table-striped\"> -->\n");
      out.write("		<table class=\"table table-dark table-striped\">\n");
      out.write("			<thead class=\"thead-dark\">\n");
      out.write("\n");
      out.write("				<tr>\n");
      out.write("					<th>Name :</th>\n");
      out.write("					<th>Category :</th>\n");
      out.write("					<th>Price :</th>\n");
      out.write("					<th>Buy Now</th>\n");
      out.write("					<th>Cancel</th>\n");
      out.write("				</tr>\n");
      out.write("\n");
      out.write("			</thead>\n");
      out.write("\n");
      out.write("			<tbody>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("				");

				if (cart_list != null) {

					for (Cart c : cartProduct) {
				
      out.write("\n");
      out.write("				<tr class=\"table-secondary\">\n");
      out.write("\n");
      out.write("\n");
      out.write("					<td>");
      out.print(c.getName());
      out.write("</td>\n");
      out.write("					<td>");
      out.print(c.getCategory());
      out.write("</td>\n");
      out.write("					<td>$");
      out.print(c.getPrice());
      out.write("</td>\n");
      out.write("					<td>\n");
      out.write("						<form action=\"orderNow\" method=\"post\" class=\"form-inline \">\n");
      out.write("\n");
      out.write("							<input type=\"hidden\" name=\"id\" value=\"");
      out.print(c.getId());
      out.write("\"\n");
      out.write("								class=\"form-input\">\n");
      out.write("\n");
      out.write("							<div class=\"form-group d-flex justify-content-center w-75 mx-2\">\n");
      out.write("\n");
      out.write("								<a class=\"btn btn-info  btn-sm btn-incre pr-2 mx-2\"\n");
      out.write("									href=\"cartIncDec?action=inc&id=");
      out.print(c.getId());
      out.write("\"> <i\n");
      out.write("									class=\"fa-solid fa-plus\"></i></a> <input type=\"text\"\n");
      out.write("									name=\"quantity\" class=\"form-control\"\n");
      out.write("									value=\"");
      out.print(c.getQuantity());
      out.write("\" readonly> <a\n");
      out.write("									class=\"btn btn-danger btn-sm btn-decre mx-2\"\n");
      out.write("									href=\"cartIncDec?action=dec&id=");
      out.print(c.getId());
      out.write("\"> <i\n");
      out.write("									class=\"fa-solid fa-minus\"></i></a>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("								<button class=\"btn btn-sm btn-secondary mr-2\">Buy</button>\n");
      out.write("\n");
      out.write("\n");
      out.write("							</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("						</form>\n");
      out.write("\n");
      out.write("\n");
      out.write("					</td>\n");
      out.write("\n");
      out.write("					<td><a class=\"btn btn-sm btn-danger\"\n");
      out.write("					href=\"removeFromCart?id=");
      out.print(c.getId());
      out.write("\">Remove</a></td>\n");
      out.write("\n");
      out.write("				</tr>\n");
      out.write("				");

				}
				}
				
      out.write("\n");
      out.write("\n");
      out.write("			</tbody>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("		</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("	</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
